# travis-ci.org build & test configuration
language: cpp

compiler:
  - clang
  - gcc

env:
  matrix:
    - ROOT=5-34-18
    - ROOT=6-00-00
  global:
    - CLANG_VERSION=3.6

before_install: source ci/before_install.sh
install: source ci/install.sh
script: bash ci/test.sh
cache: apt
