#!/usr/bin/env python
'''
Created on 7 Jun 2010

@author: kreczko

Email: kreczko@cern.ch
'''
import sys
try:
    import subprocess
except:
    print "You have to use Python 2.4 or higher"
    sys.exit(0)
from optparse import OptionParser

srmBase = 'srm://lcgse02.phy.bris.ac.uk:8444/srm/managerv2?SFN='

def getFiles(gridFolder, input):
    if gridFolder.endswith('/'):
        gridFolder = gridFolder.rstrip('/')
    input = input.rstrip(' ')
    fileLinesOnly = input[input.find(gridFolder)+len(gridFolder):]
    fileLines = fileLinesOnly.split('\n')[1:]
    fileLines = [fileLine.lstrip(' ') for fileLine in fileLines]
    files = [line.split(' ')[1] for line in fileLines if len(line.split(' ')) == 2]
    files.sort()
    return files
    
def listFiles(gridFolder):
    output = subprocess.Popen(['srmls', srmBase + gridFolder], stdout = subprocess.PIPE).communicate()[0]
    return output
    
def delete(file):
    output = subprocess.Popen(['srmrm', srmBase + file], stdout = subprocess.PIPE).communicate()[0]
    return output

def deleteFolder(folder):
    output = subprocess.Popen(['srmrmdir', srmBase + folder], stdout = subprocess.PIPE).communicate()[0]
    return output
if __name__ == '__main__':
    
    parser = OptionParser()
    (options, args) = parser.parse_args()
    if len(args) >0:
        path = args[0]
        filelist = listFiles(path)
        for file in getFiles(path, filelist):
            delete(file)
            deleteFolder(path)
    else:
        print 'Delete path was not specified. Use script "./deleteGridFolder path"'
