files = {
    'data':"/storage/results/histogramFiles/PAS/data_1091.45pb_PFElectron_PF2PATJets_PFMET.root",
    'ttbar' : "/storage/results/histogramFiles/PAS/TTJet_1091.45pb_PFElectron_PF2PATJets_PFMET.root",
    'wjets' : "/storage/results/histogramFiles/PAS/WJetsToLNu_1091.45pb_PFElectron_PF2PATJets_PFMET.root",
    'zjets' : "/storage/results/histogramFiles/PAS/DYJetsToLL_1091.45pb_PFElectron_PF2PATJets_PFMET.root",
    'bce1' : "/storage/results/histogramFiles/PAS/QCD_Pt-20to30_BCtoE_1091.45pb_PFElectron_PF2PATJets_PFMET.root",
    'bce2' : "/storage/results/histogramFiles/PAS/QCD_Pt-30to80_BCtoE_1091.45pb_PFElectron_PF2PATJets_PFMET.root",
    'bce3' : "/storage/results/histogramFiles/PAS/QCD_Pt-80to170_BCtoE_1091.45pb_PFElectron_PF2PATJets_PFMET.root",
    'enri1' : "/storage/results/histogramFiles/PAS/QCD_Pt-20to30_EMEnriched_1091.45pb_PFElectron_PF2PATJets_PFMET.root",
    'enri2' : "/storage/results/histogramFiles/PAS/QCD_Pt-30to80_EMEnriched_1091.45pb_PFElectron_PF2PATJets_PFMET.root",
    'enri3' : "/storage/results/histogramFiles/PAS/QCD_Pt-80to170_EMEnriched_1091.45pb_PFElectron_PF2PATJets_PFMET.root",
    'pj1' : "/storage/results/histogramFiles/PAS/GJets_TuneD6T_HT-40To100_1091.45pb_PFElectron_PF2PATJets_PFMET.root",
    'pj2' : "/storage/results/histogramFiles/PAS/GJets_TuneD6T_HT-100To200_1091.45pb_PFElectron_PF2PATJets_PFMET.root",
    'pj3' : "/storage/results/histogramFiles/PAS/GJets_TuneD6T_HT-200_1091.45pb_PFElectron_PF2PATJets_PFMET.root",
    'tW' : "/storage/results/histogramFiles/PAS/TToBLNu_TuneZ2_tW-channel_1091.45pb_PFElectron_PF2PATJets_PFMET.root",
    'tchan' : "/storage/results/histogramFiles/PAS/TToBLNu_TuneZ2_t-channel_1091.45pb_PFElectron_PF2PATJets_PFMET.root",
    'ww' : "/storage/results/histogramFiles/PAS/WWtoAnything_1091.45pb_PFElectron_PF2PATJets_PFMET.root",
    'wz' : "/storage/results/histogramFiles/PAS/WZtoAnything_1091.45pb_PFElectron_PF2PATJets_PFMET.root",
    'zz' : "/storage/results/histogramFiles/PAS/ZZtoAnything_1091.45pb_PFElectron_PF2PATJets_PFMET.root",
             }